# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'cliente',
            },
        ),
    ]
