# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
